### ISSUE TITLE
Exercise 1 To-do list

### ISSUE THREAD

**Issue by nicholaspalomo** [nicholaspalomo/VisionAlgosCourseETHZ#1]
- [ ] Finish Part 3 of Exercise 1 (filtering).
- [ ] Use the ad-hoc animation functionality in Matplotlib.
- [ ] Add argparsing where it makes sense.
- [ ] Create Doxygen comments.
- [ ] Vectorize operations where in makes sense, in order to gain speed improvements.
- [ ] Clean up code where possible and put things in to functions where it makes sense.
