### ISSUE TITLE
Exercise 2 To-do list

### ISSUE THREAD

**Issue by nicholaspalomo** [nicholaspalomo/VisionAlgosCourseETHZ#2]
- [x] Code for first two bullet points of DLT implementation section of Exercise 2 is running, but results not correct (points not showing up in the right place.
- [x] Need to produce the animation for bullet point 3 -> See also: https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.quiver.html
- [ ] Need to do code cleanup -> move methods to the empty files I created (as necessary).
- [ ] Add comments; generate doxygen documentation.
